### ISSUE TITLE
Assemble Habarama

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#199]
As a developer I want to assemble all the parts and connect the sensors so that I have a functional prototype. Since this is just a first test, there is no need for soldering components yet.

**Acceptance Criteria**
- [x] All parts are assembled via breadboard representing a functional prototype.
- [x] Each Habarama is connected to a single sensor.

**Tasks**
- [x] Assemble parts
- [x] Connect sensors

**Comment by ludwigSteindl** [comment]
@ErhardSiegl How many prototypes do we want to build at first? I'd suggest at least 3-4.

**Comment by ErhardSiegl** [comment]
Depends how "prototypish" it is. With breadboard, soldered, printed circuit board? Who will work with / use the prototype?

**Comment by ludwigSteindl** [comment]
@ErhardSiegl see #198 . I strongly suggest to order and compare a few (at least 2-3) different micro-controllers in order to be flexible if (or better when) a problem with a certain component emerges. Also, we want to experiment with different components to evaluate component size and power consumption. 
At this stage, the prototype is very prototypish, it is realized as a breadboard circuit and only the hardware team is using the prototype.

**Comment by ErhardSiegl** [comment]
OK, I thought you ment how many of the same kind. Maybe you try one sensor-only, one actor-only and one with sensor and actor attached.
