### ISSUE TITLE
Rewrite Habarama code (python)

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#202]
As a developer, I want the Habarama's source code to be re-written in an Arduino-based machine language (i.e. Arduino IDE), so I can use it on any Arduino-based microcontroller.

**Acceptance Criteria**
- [x] Code for Habaramas is written in language compatible with any Arduino-based microcontroller.
- [ ] Current functionality of the RaspberryPi-based prototype is provided in the new environment.

**Tasks**
- [x] Determine language
- [ ] Rewrite code

**Hint**
see https://github.com/Tharnas/habarama-esp8266

**Comment by fhochleitner** [comment]
TODO: do not send dummy values to queue

**Comment by SabrinaPloner** [comment]
@fhochleitner @ludwigSteindl status?

**Comment by fhochleitner** [comment]
potentially finished. arduino's can be setup with wifi, reset wifi connection by button press, read and send sensor values and actors are implemented as well. however, we have never tried out if the code for the pump activation works because we only have one pump which is used for our production unit. 

maybe @johannesr124 knows more as he has worked on it as well
