### ISSUE TITLE
Fluentd looses connection to mongodb

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#208]
Once in a while no new data arrive in MongoDB. Ater restart of Fluentd pod it works again. Fluentd seems to loose connection to Mongo. A reason might be that Mongo restarts (maybe not enough memory) but still Fluentd should keep working after a Mongo restart.

**Comment by muhlba91** [comment]
mongodb uses memory caching quite extensively and holds a whole lot of data in there (see, e.g., https://dba.stackexchange.com/a/148397) -> in fact, the more data mongodb has to actively handle, the more memory it will consume.

In this case, because mongodb contains periodic measurements leading to increased dataset sizes over time, it is apparent the limit of 512MB as defined in https://github.com/Gepardec/Hogarama/blob/master/Templates/dc/mongodb_dc.yaml#L71 does not suffice for too long, especially when also queries are made against it.

Generally speaking, limiting the main/core database memory too much - if it relies heavily on caching and in-memory data - might not be a good practice as the database running OOM will most likely result in a „crashloop“ or, at least, performance issues within the entire system.
Therefore, introducing some kind of automated archiving and/or aggregation to a different datastore, pruning or similar feature could mitigate the increasing memory requirements. Also, since Prometheus receives the measurements as well, it could function as the main (live) database for this kind of data?
Hence, a suggestion is to use Prometheus for short to, possibly, medium time storage depending on its needed resources and application requirements and aggregate historical data into mongodb as necessary.

**Comment by ErhardSiegl** [comment]
Thanks for your suggestions. We also saw recently, that we run into problems with long query times coming mainly from prometheus. See #214. Using mongo only for configuration and prometheus or something else for sensor data might be a good alternative.

**Comment by muhlba91** [comment]
Yes indeed. #214 is related to this - mongodb has to to an entire collection scan; in fact, putting the entire data into memory and then extract and unique the result, especially without indexes.
However, in what aspects did you get slow query results from Prometheus?

As said, I also didn‘t find any defined indexes on the mongodb collection. Defining additional indexes on e.g. sensorName and time will already help already with query performance, although I‘m not entirely sure about the memory aspects.

Anyhow, sensor data is, basically, a time series based data; hence, using Prometheus, InfluxDB or equivalent is a better choice than mongodb. (I believe even a properly indexed SQL datasource could be better in this case.)
Whether any sort of archiving/aggregation to a different datasource for long term storage to reduce Prometheus‘ dataset and probably memory/cpu requirements will be seen once it fills up with data.
However, storing sensor, location, etc. metadata in a different database can also be worth consideration since this is most likely „static information“ and could in future use cases be altered/provided by the user through the UI.

**Comment by fhochleitner** [comment]
The slow queries have not been identified using prometheus but by examining the mongodb pods log, which showed simply queries taking between 5 to 10 seconds and other queries taking up to 25s. 

As a first countermeasure i have set mongoDbs max memory to 1.5gb from 1gb and added 3 additional indexes - even though it said the index on sensorName already existed. 

At a first glance it appears as though these measures did work as the frontend is able to load mongodb data as well and query execution time seems to have drastically improved as well

**Comment by fhochleitner** [comment]
edit for anyone interested. query times are down to 150ms to 840ms with an average of about 450ms
