### ISSUE TITLE
Angular-Ionic integration

### ISSUE THREAD

**Issue by ludwigSteindl** [Gepardec/Hogarama#237]
As a developer I want to make usage of Ionic to provide better mobile solutions.

Acceptance criteria:
- [x] Integrate existing angular code into Ionic (e.g. authentication)
- [x] OpenShift deployment
- [x] Android build & test
- [ ] iOS build & test

**Comment by MauriceNino** [comment]
Someone else needs to test this branch on IOS.

**Comment by ErhardSiegl** [comment]
Regarding commit 7d307c3 and files in Templates/local_wildfly/: I don't think its useful to do wildfly-config twice on different places. It is already in ./Hogajama/configuration/local_configuration/ which works with https://github.com/Gepardec/JBSS

**Comment by MauriceNino** [comment]
@ErhardSiegl You can delete my solution and update the docs so that everyone can install his local dev environment on Windows **and** Linux. Also, the modules for keycloak and postgres (plus its entries in the `standalone.xml`) need to be added to your scripts. For reference, feel free to check my solution.

@ludwigSteindl Someone still needs to test this on IOS, if that is still an Acceptance Criteria.

@SabrinaPloner The pull request is accepted and everything seems to work fine. If everything is ok, this ticket can be moved to "Done".

**Comment by ErhardSiegl** [comment]
@MauriceNino The local JBoss development is already documented in https://github.com/Gepardec/Hogarama/wiki/Local-JBoss-Development
