### ISSUE TITLE
GUI für Sensorverwaltung übernehmen

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#285]
Take the classes / angular gui from IoT and integrate it into master

**Comment by eerofeev** [comment]
Are 3 SP for you ok @MauriceNino and @MauriceNino1 ?

**Comment by MauriceNino** [comment]
What is meant with this? @eerofeev 

1. Rewrite the GUI to also fit the older version of Hogarama

**or**

2. Just copy & paste it, so that it works for the IOT part of Hogarama

Also, you can remove @MauriceNino1 from the project as well as the Gepardec Team.

**Comment by eerofeev** [comment]
>     1. Just copy & paste it, so that it works for the IOT part of Hogarama

Actually we need the new GUI, so it should be transferred to the master.
You can create the new branch from master and copy the needed sources. Then we will merge it via a merge request.

**Comment by MauriceNino** [comment]
@eerofeev I understood that the new Ionic GUI should be "merged" into the master am I correct?

In that case I need to know if I should simply copy and paste it into the master branch so that it works for the newer IOT project (arduino) **OR** if it should be adapted to also work with the old part (raspberries). 

The first one would only take less than 1 SP I guess. The second one is hard to decide, because I dont know the old version (rasp) that well. But I guess 3 SP would fit well.

**Comment by eerofeev** [comment]
@MauriceNino you should simply copy and paste it into the master branch so that it works for the newer IOT project (arduino)

**Comment by MauriceNino** [comment]
@eerofeev Then you can label it as 1 SP as it will be a work of less than 2h I would guess.

**Comment by fhochleitner** [comment]
hold on a second. old functionality should not be broken. so data from raspberries should still be visible on our frontend. at least if i understood our PO correctly. @ErhardSiegl

**Comment by MauriceNino** [comment]
It will still be visible on the old frontend. If the raspberries start to work with the new backend services, it will also work with the new frontend. But integrating two different backend types in one frontend would be a lot more work. Also I dont know if it even is possible, because the old version lacks an owner which is a crucial part of the new frontend.

**Comment by fhochleitner** [comment]
as long as there is still a way to view the raspberries data it should'nt be a problem.

**Comment by MauriceNino** [comment]
me copying the new frontend should not affect the existing system at all.

**Comment by ErhardSiegl** [comment]
We have no "Sensorverwaltung" for current Hogarama (Raspi). The only configuration we have is a watering-config, which is not part of that usecase.

**Comment by ErhardSiegl** [comment]
@MauriceNino  On which URL is the GUI visible?

**Comment by MauriceNino** [comment]
@ErhardSiegl it _should_ be reachable from the sub-url `hogajama-angular-frontend`, but I can't 100% confirm it right now, as I am not on my laptop right now.

**Comment by ErhardSiegl** [comment]
Context in hogajama-frontend is "/":
```
$ cat  ./hogajama-frontend/src/main/webapp/WEB-INF/jboss-web.xml
<jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://www.jboss.org/j2ee/schema/jboss-web_6_0.xsd"
	version="6.0">
	<context-root>/</context-root>
	<security-domain>keycloak</security-domain>
</jboss-web>
```
and context in hogajama-angular-frontend is "/":
```
$ cat ./hogajama-angular-frontend/src/main/webapp/WEB-INF/jboss-web.xmlb.xml
<jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://www.jboss.org/j2ee/schema/jboss-web_6_0.xsd"
           version="6.0">
    <context-root>/</context-root>
</jboss-web>
```
How can this work?
