### ISSUE TITLE
Sprintziel: Anzeigen der vorhandenen Sensoren (nicht Sensordaten) im "neuen" GUI

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#290]

**Comment by MauriceNino** [comment]
TODO:

- When transmitting the SSID and password to the arduino, also send the userId (or a single-use code that is generated specifically for this action)
- This code will then be sent to our backend as the first action

With this the hardware would be connected to the user and shown in the GUI (in reality, sensors are already shown in the GUI, there is just no hardware behind it)

**Comment by fhochleitner** [comment]
@MauriceNino does this make the old approach of sending the MAC-address of the arduinos wifi chip obsolete? 
As far as I know the plan was to use this unique address in order to uniquely identify arduino instances and for mapping them to a user. 

Generating a different id is also a working approach but in my opinion using something that is inherently unique, already available and which is already implemented to be sent together with the payload anyways would be a more feasible approach.

**Comment by MauriceNino** [comment]
I mean this is something that just came to my head when thinking about the problem, but I have forgotten about the MAC address way to be honest.

I think the single-use code way would be user friendlier, as he does not have to enter a long string of characters into his device (or scan the QR code in case he is on a mobile phone). Also, I think it would be a bit safer as the code would be generated shortly before it will be sent to the backend so there is a smaller gap for stuff like "already used MACs that are stolen by someone else" happening.

What do you think about this @fhochleitner ?

**Comment by fhochleitner** [comment]
Both implementations have advantages as well as disadvantages. Stolen MACs doesn't seem like an as they should be unique anyways and will be read and sent directly by the microcontroller without user input. The only issue I see with using MAC addresses would be the way to inform the user about the mac-addresses value so the user can map devices to his/her account .

**Comment by MauriceNino** [comment]
I see a few different problems with MAC addresses.

1. Some user could just spoof MAC addresses and add them to his account. When the user who bought one of the arduinos with an already added MAC address tries to add it to his account, it won't be possible
2. The issue is not how to show him (that could be done by a sticker with a QR code and the MAC printed on it), but rather that he has to input it manually, which is kind of tedious task if you ask me

I mean in the end it is not that big of a security issue as I make it sound, because guessing a MAC address for something as small as this, is like searching for the needle in the haystack.

But on the other hand "my" way has a few advantages.

1. Its generated on the fly and has a short living time, making it close to impossible for someone to steal your info. And even if that would happen, the fake arduino gets added to your account which can be removed easily. But there is no way that someone adds your arduino to his account.
2. This communication can be done in the background, as the application will just send the code with the ssid and password,

**Comment by MauriceNino** [comment]
Also, if I remember correctly we were already talking about making the sign up process a bit more secure, so it was already matter to change anyways.

**Comment by eerofeev** [comment]
In this sprint we do not use the mac adresses at all. The goal is to show the existing sensors in the new gui. For this purpose we will use the old sensor names as the ID. The name, that will be shown in the GUI and in the Prometheus must be defined in the GUI itself (Sensor management).

Regarding security: there is already idea of inital concept:
https://github.com/Gepardec/Hogarama/issues/259

**Comment by MauriceNino** [comment]
Are you sure about that? Last time we spoke about this, it was said, that this is about the new sensors and for the old ones prometheus is enough. @eerofeev

**Comment by eerofeev** [comment]
Yes, i think the sprint goal identifies it quite well. We must be able to see the existing sensors (not their data) in the neu GUI. What are yor concerns?

**Comment by MauriceNino** [comment]
@eerofeev That this was a question I specifically asked when creating this issue and @ErhardSiegl said that it is about the new Arduinos being connected to the frontend, so that there are not only dummy sensors/actors shown. For the old Raspberries it is enough if you can still view them in Prometheus as far as I remember.

**Comment by eerofeev** [comment]
@MauriceNino The old sensors will be added to the management database manually, so they will be visible in the new gui. After that we will be able to give them their new names (since the old ones are used as IDs). Then they will be visible in the prometheus under the new names.
Please contact @ErhardSiegl directly to clarify this point.

**Comment by ErhardSiegl** [comment]
> @MauriceNino The old sensors will be added to the management database manually, so they will be visible in the new gui. After that we will be able to give them their new names (since the old ones are used as IDs). Then they will be visible in the prometheus under the new names.
> Please contact @ErhardSiegl directly to clarify this point.

That is my understanding. We would need a description or script how to insert the old sensors into the database.
