### ISSUE TITLE
1024 Staging: Provide Templates for runtime-only

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#57]
It should be possible to create a new runtime-environment (no build) out of templates with a command similar to: oc create -f horarama-runtime.yaml

**Comment by Montecito** [comment]
Don't forget to set the "STAGE" env var as mentioned in #59

**Comment by sjutz** [comment]
oc process -f <template-name> | oc create -f -

**Comment by sjutz** [comment]
Persistent Volume Claim is no longer stuck in the pending state. However, for presentation purposes we need to make sure that this problem does not occur any more.

Now, the sensor data presentation page (frontend) is stuck because there is no data in the database. 
![hogarama](https://user-images.githubusercontent.com/11520909/28663728-791c84d0-72be-11e7-8fcd-9deac97ca7f7.png) As soon as the collection habarama and one sensor data entry is added, the page loads correctly (also the stage and pod-id). 
Can someone fix this issue by tomorrow (eg show hint that no sensor data is available)?

**Comment by sjutz** [comment]
For usage, see https://github.com/Gepardec/Hogarama/wiki/OpenShift-Templates#how-to-create-a-new-hogarama-instance-from-a-template
